// ! Do Not Edit This File

import { Icons } from "../icons";

export const FunctionalUnfavoriteButton = ({
  onClick,
}: {
  onClick: () => void;
}) => (
  <img
    src={Icons.Heart}
    alt=""
    className="unfavorite-button"
    style={{ width: 40, border: 0 }}
    onClick={() => {
      onClick();
    }}
  />
);
